//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingSite.CreditCardApplicationServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCardApplication", Namespace="http://schemas.datacontract.org/2004/07/BankingSite.Model.DomainEntities")]
    [System.SerializableAttribute()]
    public partial class CreditCardApplication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AirlineFrequentFlyerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApplicantAgeInYearsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicantNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AirlineFrequentFlyerNumber {
            get {
                return this.AirlineFrequentFlyerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AirlineFrequentFlyerNumberField, value) != true)) {
                    this.AirlineFrequentFlyerNumberField = value;
                    this.RaisePropertyChanged("AirlineFrequentFlyerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApplicantAgeInYears {
            get {
                return this.ApplicantAgeInYearsField;
            }
            set {
                if ((this.ApplicantAgeInYearsField.Equals(value) != true)) {
                    this.ApplicantAgeInYearsField = value;
                    this.RaisePropertyChanged("ApplicantAgeInYears");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicantName {
            get {
                return this.ApplicantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicantNameField, value) != true)) {
                    this.ApplicantNameField = value;
                    this.RaisePropertyChanged("ApplicantName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmissionResult", Namespace="http://schemas.datacontract.org/2004/07/BankingSite.Model.DomainEntities")]
    [System.SerializableAttribute()]
    public partial class SubmissionResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ValidationErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReferenceNumber {
            get {
                return this.ReferenceNumberField;
            }
            set {
                if ((this.ReferenceNumberField.Equals(value) != true)) {
                    this.ReferenceNumberField = value;
                    this.RaisePropertyChanged("ReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ValidationErrors {
            get {
                return this.ValidationErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationErrorsField, value) != true)) {
                    this.ValidationErrorsField = value;
                    this.RaisePropertyChanged("ValidationErrors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreditCardApplicationServiceReference.ICreditCardApplicationService")]
    public interface ICreditCardApplicationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardApplicationService/SubmitApplication", ReplyAction="http://tempuri.org/ICreditCardApplicationService/SubmitApplicationResponse")]
        BankingSite.CreditCardApplicationServiceReference.SubmissionResult SubmitApplication(BankingSite.CreditCardApplicationServiceReference.CreditCardApplication application);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardApplicationService/SubmitApplication", ReplyAction="http://tempuri.org/ICreditCardApplicationService/SubmitApplicationResponse")]
        System.Threading.Tasks.Task<BankingSite.CreditCardApplicationServiceReference.SubmissionResult> SubmitApplicationAsync(BankingSite.CreditCardApplicationServiceReference.CreditCardApplication application);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardApplicationService/GetSuccesfulApplicantsName", ReplyAction="http://tempuri.org/ICreditCardApplicationService/GetSuccesfulApplicantsNameRespon" +
            "se")]
        string GetSuccesfulApplicantsName(int submissionReferenceResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardApplicationService/GetSuccesfulApplicantsName", ReplyAction="http://tempuri.org/ICreditCardApplicationService/GetSuccesfulApplicantsNameRespon" +
            "se")]
        System.Threading.Tasks.Task<string> GetSuccesfulApplicantsNameAsync(int submissionReferenceResult);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditCardApplicationServiceChannel : BankingSite.CreditCardApplicationServiceReference.ICreditCardApplicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditCardApplicationServiceClient : System.ServiceModel.ClientBase<BankingSite.CreditCardApplicationServiceReference.ICreditCardApplicationService>, BankingSite.CreditCardApplicationServiceReference.ICreditCardApplicationService {
        
        public CreditCardApplicationServiceClient() {
        }
        
        public CreditCardApplicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditCardApplicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardApplicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardApplicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BankingSite.CreditCardApplicationServiceReference.SubmissionResult SubmitApplication(BankingSite.CreditCardApplicationServiceReference.CreditCardApplication application) {
            return base.Channel.SubmitApplication(application);
        }
        
        public System.Threading.Tasks.Task<BankingSite.CreditCardApplicationServiceReference.SubmissionResult> SubmitApplicationAsync(BankingSite.CreditCardApplicationServiceReference.CreditCardApplication application) {
            return base.Channel.SubmitApplicationAsync(application);
        }
        
        public string GetSuccesfulApplicantsName(int submissionReferenceResult) {
            return base.Channel.GetSuccesfulApplicantsName(submissionReferenceResult);
        }
        
        public System.Threading.Tasks.Task<string> GetSuccesfulApplicantsNameAsync(int submissionReferenceResult) {
            return base.Channel.GetSuccesfulApplicantsNameAsync(submissionReferenceResult);
        }
    }
}
